services:
  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_assets:/app/staticfiles
    ports:
      - 80:80
    depends_on:
      - api
    container_name: nginx
  api:
    build:
      context: ./
    volumes:
      - static_assets:/app/staticfiles
    restart: on-failure
    container_name: backend
    expose:
      - 8000
    environment:
      - DJANGO_SECRET_KEY=test_key_insecure
      - DB_NAME=TestDB
      - DB_USER=test_user
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=3306
      - DEBUG=True
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=TestDB
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    container_name: db

volumes:
  static_assets:
