services:
  nginx:
    image: undeadoutlook/petpal-demo-nginx:0.1.0
    volumes:
      - static_assets:/app/staticfiles
    ports:
      - 80:80
    depends_on:
      - api
    container_name: nginx
  api:
    image: undeadoutlook/petpal-demo-api:0.1.0
    volumes:
      - static_assets:/app/staticfiles
    restart: on-failure
    container_name: backend
    expose:
      - 8000
    env_file: .env

volumes:
  static_assets:
