services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_assets:/app/staticfiles
    ports:
      - 80:80
    depends_on:
      - api
    container_name: nginx
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - static_assets:/app/staticfiles
    restart: on-failure
    container_name: backend
    expose:
      - 8000
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DEBUG=False

volumes:
  static_assets:
