services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - api
    container_name: nginx
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: on-failure
    container_name: backend
    expose:
      - 8000
