services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_assets:/app/staticfiles
    ports:
      - 80:80
    depends_on:
      - api
    container_name: nginx
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - static_assets:/app/staticfiles
    restart: on-failure
    container_name: backend
    expose:
      - 8000

volumes:
  static_assets:
