# Generated by Django 4.0.4 on 2022-05-19 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_species_rename_petcategories_petcategory_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pets.breed'),
        ),
    ]
