# Generated by Django 4.0.4 on 2022-05-19 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.ForeignKey(default=None, limit_choices_to={'category': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.petcategory')}, on_delete=django.db.models.deletion.CASCADE, to='pets.breed'),
        ),
    ]
