# Generated by Django 4.0.4 on 2022-05-19 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_pet_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='weight',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pets.breed'),
        ),
    ]
