# Generated by Django 4.0.4 on 2022-05-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
        ('pets', '0005_pet_weight_alter_pet_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='meals',
            field=models.ManyToManyField(to='meals.meal'),
        ),
    ]
