# Generated by Django 4.0.4 on 2022-05-19 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0006_pet_meals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('pet_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.petcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_units', models.CharField(choices=[('pills', 'pills'), ('ccs', 'ccs'), ('drops', 'drops')], max_length=10)),
                ('time', models.TimeField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.medicine')),
            ],
        ),
    ]
