# Generated by Django 4.0.4 on 2022-05-20 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0001_initial"),
        ("medications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medication",
            name="pet",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="pets.pet"
            ),
            preserve_default=False,
        ),
    ]
