name: Production Deployment

on:
  push:
    branches: ['main']

jobs:
  build:
    name: Build Django
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python (3.11)
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependecies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d # Install all dependencies, including development ones

  docker:
    name: Build and Push Containers
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          # Username used to log against the Docker registry
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build container images
        run: |
          docker build -t petpal/demo-api ./api
          docker build -t petpal/demo-nginx ./nginx

      - name: Tag images
        run: |
          docker tag petpal/demo-api ${{ secrets.DOCKERHUB_USERNAME }}/petpal-demo-api:${{ github.sha }}
          docker tag petpal/demo-api ${{ secrets.DOCKERHUB_USERNAME }}/petpal-demo-api:latest
          docker tag petpal/demo-api ${{ secrets.DOCKERHUB_USERNAME }}/petpal-demo-api:0.1.0
          docker tag petpal/demo-nginx ${{ secrets.DOCKERHUB_USERNAME }}/petpal-demo-nginx:${{ github.sha }}
          docker tag petpal/demo-nginx ${{ secrets.DOCKERHUB_USERNAME }}/petpal-demo-nginx:latest
          docker tag petpal/demo-nginx ${{ secrets.DOCKERHUB_USERNAME }}/petpal-demo-nginx:0.1.0

      - name: Push to DockerHub
        run: |
          docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/petpal-demo-api
          docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME}}/petpal-demo-nginx

  deploy:
    name: Deploy to ECS
    runs-on: ubuntu-latest
    needs:
      - build
      - docker

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create ECS Context
        run: |
          docker context create ecs petpal-ecs
          docker context use petpal-dev

      - name: Test CloudFormation template
        run: docker compose convert

      - name: Deploy Cluster Resources
        run: docker compose up
