name: Production Deployment

on:
  push:
    branches: ['main']

jobs:
  build:
    name: Build Django
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python (3.11)
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependecies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d # Install all dependencies, including development ones

  docker:
    name: Build and Push Containers
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          # Username used to log against the Docker registry
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build container images
        run: |
          docker build -t django-api ./api
          docker build -t django-nginx ./nginx

      - name: Tag images
        run: |
          docker tag django-api ${{ secrets.DOCKERHUB_USERNAME }}/petpal-django-api:${{ github.sha }}
          docker tag django-api ${{ secrets.DOCKERHUB_USERNAME }}/petpal-django-api:latest
          docker tag django-api ${{ secrets.DOCKERHUB_USERNAME }}/petpal-django-api:0.1.0
          docker tag django-nginx ${{ secrets.DOCKERHUB_USERNAME }}/petpal-django-nginx:${{ github.sha }}
          docker tag django-nginx ${{ secrets.DOCKERHUB_USERNAME }}/petpal-django-nginx:latest
          docker tag django-nginx ${{ secrets.DOCKERHUB_USERNAME }}/petpal-django-nginx:0.1.0

      - name: Push to DockerHub
        run: |
          docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/petpal-django-api
          docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME}}/petpal-django-nginx

  deploy:
    name: Push to S3
    runs-on: ubuntu-latest
    needs:
      - build
      - docker

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Compress Source Code
        run: zip -r source.zip ./

      - name: Archive Source Code
        uses: actions/upload-artifact@v3
        with:
          name: Compressed Source (.zip)
          path: ./source.zip

      - name: Push to S3
        run: aws s3 cp source.zip s3://django-api-source-code
